site_name: xTrain API
site_url: https://chatelao.github.io/xDuinoRails_xTrainAPI/
repo_url: https://github.com/chatelao/xDuinoRails_xTrainAPI
theme:
  name: readthedocs

docs_dir: site_source
site_dir: public

nav:
  - Home: index.md
  - CLI Syntax: docs/CLI_SYNTAX.en.md
  - Glossary: XTTRAIN_GLOSSARY.en.md
  - Data Dictionary: DATA_DICTIONARY.en.md
  - Open Issues: OPEN_ISSUES.en.md
  - API Reference: docs/API_LINKS.en.md
